plugins {
    id 'java'
    id 'io.qameta.allure' version '3.0.1'
}

def allureVersion = "2.24.0"

allure {
    report {
        version.set(allureVersion)
    }
    adapter {
        aspectjWeaver.set(true)
        frameworks {
            junit5 {
                adapterVersion.set(allureVersion)
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation "io.qameta.allure:allure-junit5:$allureVersion"
    testImplementation "io.qameta.allure:allure-selenide:$allureVersion"
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'com.codeborne:selenide:7.13.0'
    testImplementation 'net.datafaker:datafaker:2.5.3'
    testImplementation 'org.aeonbits.owner:owner:1.0.12'
}

test {
    useJUnitPlatform()
    systemProperties(System.getProperties())
}

/*
task smokeTest(type: Test) {
    useJUnitPlatform {
        includeTags 'SMOKE'
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
    }
}

task positiveTest(type: Test) {
    useJUnitPlatform {
        includeTags 'POSITIVE'
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
    }
}

task negativeTest(type: Test) {
    useJUnitPlatform {
        includeTags 'NEGATIVE'
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
    }
}

task loginTest(type: Test) {
    useJUnitPlatform {
        includeTags 'LOGIN'
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
    }
}

task cartTest(type: Test) {
    useJUnitPlatform {
        includeTags 'CART'
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
    }
}

task registrationTest(type: Test) {
    useJUnitPlatform {
        includeTags 'REGISTRATION'
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
    }
}

task stepicTest(type: Test) {
    useJUnitPlatform {
        includeTags 'STEPIK'
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
    }
}

task bulgakovTest(type: Test) {
    useJUnitPlatform {
        includeTags 'BULGAKOV'
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
    }

    tasks.withType(Test) {
        systemProperties(System.getProperties())
    }
}
 */

task uiTest(type: Test) {
    useJUnitPlatform {
        // Читаем параметр "tag", который мы передадим при запуске (например, -Dtag=positive)
        def tag = System.getProperty("tag")

        // Логика фильтрации тестов:
        // Если тэг указан — запускаем тесты, где есть одновременно тег "UI" И наш указанный тэг
        // Если тэг не указан — запускаем вообще все тесты с тегом "UI"
        if (tag != null && !tag.isBlank()) {
            includeTags("UI & ${tag}")
        } else {
            includeTags("UI")
        }
    }
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    systemProperties(System.getProperties())
}

task apiTest(type: Test) {
    useJUnitPlatform {
        def tag = System.getProperty("tag")

        if (tag != null && !tag.isBlank()) {
            includeTags("API & ${tag}")
        } else {
            includeTags("API")
        }
    }
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    systemProperties(System.getProperties())
}

task allTests(type: Test) {
    useJUnitPlatform {
        def tag = System.getProperty("tag")
        if (tag != null && !tag.isBlank()) {
            includeTags(tag) // Здесь НЕТ привязки к "API & UI"
        }
    }
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    systemProperties(System.getProperties())
}