    plugins {
        id 'java'
        id 'io.qameta.allure' version '3.0.1'
        id 'io.freefair.lombok' version '9.5.0'
    }

    def allureVersion = "2.24.0"

    allure {
        report {
            version.set(allureVersion)
        }
        adapter {
            aspectjWeaver.set(true)
            frameworks {
                junit5 {
                    adapterVersion.set(allureVersion)
                }
            }
        }
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        testImplementation "io.qameta.allure:allure-junit5:$allureVersion"
        testImplementation "io.qameta.allure:allure-selenide:$allureVersion"
        testImplementation "io.qameta.allure:allure-rest-assured:$allureVersion"
        testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
        testImplementation 'com.codeborne:selenide:7.13.0'
        testImplementation 'net.datafaker:datafaker:2.5.3'
        testImplementation 'org.aeonbits.owner:owner:1.0.12'
        testImplementation 'io.rest-assured:rest-assured:6.0.0'
        testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
        testImplementation 'org.assertj:assertj-core:3.27.7'
        testImplementation 'io.qameta.allure:allure-assertj:2.35.2'
    }

test {
    useJUnitPlatform()
    systemProperties(System.getProperties())
}

task smokeTest(type: Test) {
    useJUnitPlatform {
        includeTags 'SMOKE'
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
    }
}

task positiveTest(type: Test) {
    useJUnitPlatform {
        includeTags 'POSITIVE'
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
    }
}

task negativeTest(type: Test) {
    useJUnitPlatform {
        includeTags 'NEGATIVE'
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
    }
}

task loginTest(type: Test) {
    useJUnitPlatform {
        includeTags 'LOGIN'
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
    }
}

task cartTest(type: Test) {
    useJUnitPlatform {
        includeTags 'CART'
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
    }
}

task registrationTest(type: Test) {
    useJUnitPlatform {
        includeTags 'REGISTRATION'
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
    }
}

task stepicTest(type: Test) {
    useJUnitPlatform {
        includeTags 'STEPIK'
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
    }
}

task bulgakovTest(type: Test) {
    useJUnitPlatform {
        includeTags 'BULGAKOV'
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
    }

    tasks.withType(Test) {
        systemProperties(System.getProperties())
    }
}
